require_relative 'instructions/arithmetic'
require_relative 'instructions/push'
require_relative 'instructions/pop'
# require_relative 'instructions/label'
# require_relative 'instructions/goto'
# require_relative 'instructions/if'
# require_relative 'instructions/function'
# require_relative 'instructions/return'
# require_relative 'instructions/call'
